source/repos/MarketPlace/MarketPlace/Areas/Admin/Controllers/BodegasController.cs
using MarketPlace.AccesoDatos.Repository.IRepository;
using MarketPlace.Modelos;
using MarketPlace.Utilidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SistemaInventario.Utilidades;
using System.Security.Claims;

namespace MarketPlace.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Roles = DS.RoleAdmin)]
	public class BodegasController : Controller
	{
		private readonly IUnidadTrabajo _unidadTrabajo;
        private readonly UserManager<IdentityUser> _userManager;
        public BodegasController(IUnidadTrabajo unidadTrabajo, UserManager<IdentityUser> userManager)
        {
			_unidadTrabajo = unidadTrabajo;
            _userManager = userManager;
        }
        public IActionResult Index()
		{
			return View();
		}
        [HttpGet]
        public async Task<IActionResult> Upsert(int? id)
        {
            Bodega bodega = new Bodega();
            if (id == null)
            {
                //Se realiza un insert
                bodega.Status = true;
                return View(bodega);
            }
            bodega = await _unidadTrabajo.Bodega.Obtener(id.GetValueOrDefault());
            if (bodega == null)
            {
                return NotFound();
            }
            return View(bodega);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Bodega bodega)
        {
            if (!ModelState.IsValid)
            {
                //Obtener el usuario logeado

                var usuario = await _userManager.GetUserAsync(User);

                if (usuario != null)
                {
                    //asociar e producto con el  usuario
                    bodega.UsuarioAplicacionId = usuario.Id;
                }
                if (bodega.Id == 0)
                { 
                   await _unidadTrabajo.Bodega.Agregar(bodega);
                    TempData[DS.Exitosa] = "Bodega creada correctamente";
                }
                else
                {
                     _unidadTrabajo.Bodega.Actualizar(bodega);
                    TempData[DS.Exitosa] = "Bodega actualizada correctamente";
                }
               await _unidadTrabajo.Guardar();
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Error] = "Error al grabar la bodega";
            return View(bodega);
        }


        #region API
        [HttpGet]
		public async Task<IActionResult> ObtenerTodos()
		{
            var claimIdentidad = (ClaimsIdentity)User.Identity;
            var claim = claimIdentidad.FindFirst(ClaimTypes.NameIdentifier);
            var todos = await _unidadTrabajo.Bodega.ObtenerTodos(x => x.UsuarioAplicacionId == claim.Value);
			return Json(new {data = todos});
		}

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var bodegaDb = await _unidadTrabajo.Bodega.Obtener(id);
            if (bodegaDb == null)
            {
                return Json(new { success = false, message = "NO se pudo borrar la bodega" });
            }
            _unidadTrabajo.Bodega.Remover(bodegaDb);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Bodega borrada con exito" });
        }
        [ActionName("ValidarNombre")]
        public async Task<IActionResult> ValidarNombre(string nombre, int id = 0)
        {
            bool valor = false;
            var lista = await _unidadTrabajo.Bodega.ObtenerTodos();
            if (id == 0)
            {
                valor = lista.Any(b => b.Name.ToLower().Trim() == nombre.ToLower().Trim());
            }
            else
            {
                valor = lista.Any(b =>b.Name.ToLower().Trim()== nombre.ToLower().Trim() && b.Id !=id);
            }
            if (valor)
            {
                return Json(new { data = true });
            }
            return Json(new { dta = false });
        }

        #endregion
    }
}

source/repos/MarketPlace/MarketPlace/Areas/Admin/Controllers/MarcasController.cs
using MarketPlace.AccesoDatos.Repository.IRepository;
using MarketPlace.Modelos;
using MarketPlace.Utilidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;

namespace MarketPlace.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Roles = DS.RoleAdmin)]
    public class MarcasController : Controller
	{
		private readonly IUnidadTrabajo _unidadTrabajo;
        private readonly UserManager<IdentityUser> _userManager;
        public MarcasController(IUnidadTrabajo unidadTrabajo, UserManager<IdentityUser> userManager)
        {
			_unidadTrabajo = unidadTrabajo;
            _userManager = userManager;
        }
        public IActionResult Index()
		{
			return View();
		}
        [HttpGet]
        public async Task<IActionResult> Upsert(int? id)
        {
            Marca marca = new Marca();
            if (id == null)
            {
                //Se realiza un insert
                marca.Status = true;
                return View(marca);
            }
            marca = await _unidadTrabajo.Marca.Obtener(id.GetValueOrDefault());
            if (marca == null)
            {
                return NotFound();
            }
            return View(marca);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Marca marca)
        {
            if (!ModelState.IsValid)
            {
                //Obtener el usuario logeado

                var usuario = await _userManager.GetUserAsync(User);

                if (usuario != null)
                {
                    //asociar e producto con el  usuario
                    marca.UsuarioAplicacionId = usuario.Id;
                }
                if (marca.Id == 0)
                { 
                   await _unidadTrabajo.Marca.Agregar(marca);
                    TempData[DS.Exitosa] = "Marca creada correctamente";
                }
                else
                {
                     _unidadTrabajo.Marca.Actualizar(marca);
                    TempData[DS.Exitosa] = "Marca actualizada correctamente";
                }
               await _unidadTrabajo.Guardar();
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Error] = "Error al grabar la Marca";
            return View(marca);
        }


        #region API
        [HttpGet]
		public async Task<IActionResult> ObtenerTodos()
		{
            var claimIdentidad = (ClaimsIdentity)User.Identity;
            var claim = claimIdentidad.FindFirst(ClaimTypes.NameIdentifier);
            var todos = await _unidadTrabajo.Marca.ObtenerTodos(x => x.UsuarioAplicacionId == claim.Value);
			return Json(new {data = todos});
		}

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var marcaDb = await _unidadTrabajo.Marca.Obtener(id);
            if (marcaDb == null)
            {
                return Json(new { success = false, message = "NO se pudo borrar la Categoria" });
            }
            _unidadTrabajo.Marca.Remover(marcaDb);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Categoria borrada con exito" });
        }
        [ActionName("ValidarNombre")]
        public async Task<IActionResult> ValidarNombre(string nombre, int id = 0)
        {
            bool valor = false;
            var lista = await _unidadTrabajo.Marca.ObtenerTodos();
            if (id == 0)
            {
                valor = lista.Any(b => b.Name.ToLower().Trim() == nombre.ToLower().Trim());
            }
            else
            {
                valor = lista.Any(b =>b.Name.ToLower().Trim()== nombre.ToLower().Trim() && b.Id !=id);
            }
            if (valor)
            {
                return Json(new { data = true });
            }
            return Json(new { dta = false });
        }

        #endregion
    }
}

source/repos/MarketPlace/MarketPlace/Areas/Admin/Controllers/ProductosController.cs
using MarketPlace.AccesoDatos.Repository.IRepository;
using MarketPlace.Modelos;
using MarketPlace.Modelos.ViewModels;
using MarketPlace.Utilidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using NuGet.Packaging.Signing;
using System.Security.Claims;

namespace MarketPlace.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Roles = DS.RoleAdmin + "," + DS.RoleCliente)]
    public class ProductosController : Controller
	{
		private readonly IUnidadTrabajo _unidadTrabajo;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<IdentityUser> _userManager;

        public ProductosController(IUnidadTrabajo unidadTrabajo, IWebHostEnvironment webHostEnvironment, UserManager<IdentityUser> userManager)
        {
            _unidadTrabajo = unidadTrabajo;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }
        public IActionResult Index()
		{
			return View();
		}
        [HttpGet]
        public async Task<IActionResult> Upsert(int? id)
        {
            //filtrar por id de usuario
            var claimIdentidad = (ClaimsIdentity)User.Identity;
            var claim = claimIdentidad.FindFirst(ClaimTypes.NameIdentifier);
            var categoriausuario = await _unidadTrabajo.Categoria.ObtenerTodos(x => x.UsuarioAplicacionId == claim.Value);
            ProductoVM productoVM = new ProductoVM()
            {

                Producto = new Producto(),

                ListaCategorias = _unidadTrabajo.Producto.ObtenertTodosDropdownLista("Categoria"),
                ListaMarcas = _unidadTrabajo.Producto.ObtenertTodosDropdownLista("Marca"),
                ListaPadre = _unidadTrabajo.Producto.ObtenertTodosDropdownLista("Producto"),
                


        };
            if (id == null)
            {
                //Crear Producto
                productoVM.Producto.Status = true;
                return View(productoVM);
            }
            else
            {
                productoVM.Producto = await _unidadTrabajo.Producto.Obtener(id.GetValueOrDefault());
                if (productoVM.Producto == null)
                {
                    return NotFound();
                }
                return View(productoVM);
            }
           
            
        }
        [HttpPost]
        public async Task<IActionResult> Upsert(ProductoVM productoVM)
        {
            if (!ModelState.IsValid) 
            {

                //Obtener el usuario logeado
                
                var usuario =  await _userManager.GetUserAsync(User);

                if (usuario != null)
                {
                    //asociar e producto con el  usuario
                    productoVM.Producto.UsuarioAplicacionId = usuario.Id;
                }
                //Cargar Imagenes
                string webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (productoVM.Producto.Id == 0)
                {
                    //Crear
                    string upload = Path.Combine(webRootPath + DS.ImageRoute);
                    string fileName = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(files[0].FileName);

                    using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    productoVM.Producto.ImageUrl = fileName + extension;
                    await _unidadTrabajo.Producto.Agregar(productoVM.Producto);
                }
                else
                {
                    //Actualizar
                    var objProducto = await _unidadTrabajo.Producto.ObtenerPrimero(p=> p.Id == productoVM.Producto.Id, isTracking:false);
                    if (files.Count >0)
                    {
                        string upload = Path.Combine(webRootPath + DS.ImageRoute);
                        string fileName = Guid.NewGuid().ToString();
                        string extension = Path.GetExtension(files[0].FileName);

                        // Para editar se Borra la imagen anterior
                        var anteriorFile = Path.Combine(upload, objProducto.ImageUrl);

                        if (System.IO.File.Exists(anteriorFile))
                        {
                            System.IO.File.Delete(anteriorFile);
                        }
                        using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        }
                        productoVM.Producto.ImageUrl = fileName + extension;
                        

                    }// Si no se carga una imagen nueva
                    else
                    {
                        productoVM.Producto.ImageUrl = objProducto.ImageUrl;
                    }
                     _unidadTrabajo.Producto.Actualizar(productoVM.Producto);
                }
                TempData[DS.Exitosa] = "Transaccion Exitosa";
                await _unidadTrabajo.Guardar();
                return View("Index");
            }// Si algo falla
            productoVM.ListaCategorias = _unidadTrabajo.Producto.ObtenertTodosDropdownLista("Categoria");
            productoVM.ListaCategorias = _unidadTrabajo.Producto.ObtenertTodosDropdownLista("Marca");
            productoVM.ListaPadre = _unidadTrabajo.Producto.ObtenertTodosDropdownLista("Producto");
            return View(productoVM);
        }
        


        #region API
        [HttpGet]
        public async Task<IActionResult> ObtenerTodos()
        {
            var claimIdentidad = (ClaimsIdentity)User.Identity;
            var claim = claimIdentidad.FindFirst(ClaimTypes.NameIdentifier);
            var todos = await _unidadTrabajo.Producto.ObtenerTodos(x => x.UsuarioAplicacionId == claim.Value, 
                incluirPropiedades: "Categoria,Marca");
                
            return Json(new { data = todos });
        }
        //public async Task<IActionResult>Obte

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var productoDb = await _unidadTrabajo.Producto.Obtener(id);
            if (productoDb == null)
            {
                return Json(new { success = false, message = "No se pudo borrar el Producto" });
            }
            //Remover imagen

            string upload = _webHostEnvironment.WebRootPath + DS.ImageRoute;
            var anteriorFile = Path.Combine(upload, productoDb.ImageUrl);
            if (System.IO.File.Exists(anteriorFile))
            {
                System.IO.File.Delete(anteriorFile);
            }

            _unidadTrabajo.Producto.Remover(productoDb);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Producto borrado con exito" });
        }
        [ActionName("ValidarSerie")]
        public async Task<IActionResult> ValidarSerie(string serie, int id = 0)
        {
            bool valor = false;
            var lista = await _unidadTrabajo.Producto.ObtenerTodos();
            if (id == 0)
            {
                valor = lista.Any(b => b.SerialNumber.ToLower().Trim() == serie.ToLower().Trim());
            }
            else
            {
                valor = lista.Any(b =>b.SerialNumber.ToLower().Trim()== serie.ToLower().Trim() && b.Id !=id);
            }
            if (valor)
            {
                return Json(new { data = true });
            }
            return Json(new { dta = false });
        }

        #endregion
    }
}

source/repos/MarketPlace/MarketPlace/Views/Shared/_BotonesActualizarYRegresar.cshtml
@model int
<div class="d-grip gap-2 d-md-block">
    <button type="submit" class="btn btn-primary" onfocus="false" asp-route-id="@Model"><i class="bi bi-pencil-square"></i> Actualizar</button>
    <a asp-action="Index" class="btn btn-success "><i class="bi bi-arrow-return-left"></i> Regresar</a>
</div>

source/repos/MarketPlace/MarketPlace/Views/Shared/_BotonesCrearYRegresar.cshtml
<div class="d-grip gap-2 d-md-block">
    <button type="submit" class="btn btn-primary" onfocus="false"><i class="bg-info bi-plus-square-fill"></i> Crear</button>
    <a asp-action="Index" class="btn btn-success "><i class="bi bi-arrow-return-left"></i> Regresar</a>
</div>

source/repos/MarketPlace/MarketPlace/Views/Shared/_Layout.cshtml
@using MarketPlace.Utilidades
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaInventario</title>
    <link rel="shortcut icon" href="~/images//icono.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaInventario.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital@1&family=Montserrat:wght@500&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/icono.png" style="width:50px; height:50px;"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(DS.RoleAdmin) || User.IsInRole(DS.RoleCliente))
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                Contenido
                            </a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole(DS.RoleAdmin))
                                {
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Bodegas" asp-action="Index">Bodegas</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Categorias" asp-action="Index">Categorias</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Marcas" asp-action="Index">Marcas</a></li>
                                }
                                
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Productos" asp-action="Index">Productos</a></li>
                            </ul>
                        </li>
                        }
                        @if (User.IsInRole(DS.RoleAdmin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                    Usuarios
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="usuarios" asp-action="Index">Usuarios</a></li>

                                </ul>
                            </li>
                        }
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notificaciones" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SistemaInventario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

source/repos/MarketPlace/MarketPlace/Views/Shared/_Notificaciones.cshtml
@using MarketPlace.Utilidades
@if (TempData[DS.Exitosa] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[DS.Exitosa]');
    </script>
}

@if (TempData[DS.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[DS.Error]');
    </script>
}